### ISSUE TITLE
GitHub has it's own versioning implementation

### ISSUE THREAD

**Issue by Jatc252** [Wrecked256/discordbot#2]
You literally just make a new release and you don't have to fill up the repo with shit version folders.

**Comment by Wrecked256** [comment]
This isn’t an issue with the code this is me not using githubs features, however too late I might fix it if I have spare time

**Comment by Jatc252** [comment]
> 
> 
> This isn’t an issue with the code this is me not using githubs features, however too late I might fix it if I have spare time

It's not an issue with the code, it's an issue with the repo files.
